AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for testing API Gateway, Lambda, DynamoDB integration

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 5


Parameters:
    Environment:
      Type: String
      Default: dev

Resources:
  Database:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub demo.ContactArticleRecommendation.${Environment}
      KeySchema:
        - AttributeName: ContactId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ContactId
          AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 1
      Tags:
        - Key: "System"
          Value: "Test"
        - Key: "Application"
          Value: "e-commerce"

  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub demo.contact.article.recommendation.${Environment}
      Tags:
        - Key: "System"
          Value: "Test"
        - Key: "Application"
          Value: "e-commerce"

  GetRecommendationsByIdFunctionDynamo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function1
      Handler: getArticlesById.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - DynamoDBReadPolicy:
            TableName:
              !Ref Database
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /getArticlesById
            Method: get
            RestApiId: !Ref API
      Environment:
        Variables:
          STAGE: !Sub ${Environment}

  GetRecommendationsByIdFunctionS3:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function2
      Handler: getArticlesById.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - S3ReadPolicy:
            BucketName:
              !Ref MyBucket
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /getArticlesByIdS3
            Method: get
            RestApiId: !Ref API
      Environment:
        Variables:
          STAGE: !Sub ${Environment}

  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub ${Environment}

Outputs:
  RecommendationsApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"